### ISSUE TITLE
Model definition script

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/configuration_draft#2]
The entry configuration will contain a link to a script with the model definition. 
We will need to decide on the following points:

- Do we allow for links only, or also for relative paths to the configuration file.
- What's the format for the script? (Also depending on the framework.)
  - Do we require some pre-set name as entry point (like a class `Model` or a function `get_model`) or is the entry point custom (needs to be specified in the config then)?
  - Does the script need to be self-contained (i.e. can only depend on default libraries) or can it import from other code in its github repo (this is pretty common in network definitions for torch hub).
- We should also think about compatibility with the existing model zoos: [torch.hub](https://pytorch.org/docs/master/hub.html#publishing-models) and tensorflow-hub.

Forking off this issue from #1 to discuss in more detail.

**Comment by oeway** [comment]
Hi, here is what I think:
> * Do we allow for links only, or also for relative paths to the configuration file.

I think the model script path should be constrained to relative path only to simplify the implementation and there is no obvious benefit of allowing placing the model script elsewhere. For version control/ security purposes, we would like the script to stay with the configuration file.

> * What's the format for the script? (Also depending on the framework.)
>   
>   * Do we require some pre-set name as entry point (like a class `Model` or a function `get_model`) or is the entry point custom (needs to be specified in the config then)?
>   * Does the script need to be self-contained (i.e. can only depend on default libraries) or can it import from other code in its github repo (this is pretty common in network definitions for torch hub).
The first one is used by Kipoi, but I think we should make it self-contained and be able to import script from the subfolders of the same github repo (relative to the root folder of the configuration file). This allows easily zip the model folder and distribute as standalone model package.

> * We should also think about compatibility with the existing model zoos: [torch.hub](https://pytorch.org/docs/master/hub.html#publishing-models) and tensorflow-hub.
If the model script is self-contained, then it can easily be compatible with existing model zoos. Example below.
> 
> Forking off this issue from #1 to discuss in more detail.

Since we are going to have the model definition script in python, and allowing import network definition from other code in github repo. I think we should consider allowing implementing the training part and data loading in the same model script. 

As one can imagine that describing training and data loading in YAML can hardly scale to future cases (e.g. different preprocessing for multiple inputs channels, auxiliary loss, discriminators etc., imagine a multi-tasking network doing both classification and segmentation). On the other hand, all these can be easily solved by describing the training functions and data loaders in a script rather than YAML.

**Comment by oeway** [comment]
Perhaps we should combine customised field in the YAML config  and use them explicitly in the model script rather than the core library. This will allowing minimize the maintenance effort of the core library, and the model script developer can decide what can be configured with YAML.


Assuming we have the following YAML configuration file:
```yaml
####Required
version: 0.0.1
language: python
framework:
    pytorch>=1.1
    torchvision>=0.1.8
name: RESNET
description: ...
...
documentation: link/to/doc.md
model_script: model.py

#####Customized
model_weights:
        source: link/to/weights.torch
        hash: 42
training:
    loss: BinaryCrossEntropy
```

Here is the content of `model.py`
```python
import torch
import torchvision
import torch.nn as nn
from bioimage import api

config = api.getConfig()

# use model zoo
model = torchvision.models.resnet18(pretrained=True)

# load the model_weights file defined in the YAML config
weight_path = api.download(config.model_weights.source, config.model_weights.hash)
model.load_state_dict(torch.load(weight_path))

# use the customized config in the YAML config
if config.training.loss == 'BinaryCrossEntropy':
    criterion = nn.BCELoss()
elif config.training.loss == 'MSE':
    criterion = nn.MSE()

def normalize(images):
    means = images.mean(dim=1, keepdim=True)
    stds = images.std(dim=1, keepdim=True)
    normalized_images = (images - means) / stds
    return normalized_images

def train(images, target):
    normalized_images = normalize(images)
    output = model(normalized_images)
    loss = criterion(output, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

def predict(images):
    normalized_images = normalize(images)
    output = model(images)

api.register(
     for='ilastik',
     type='model',
     input_shape=[None, 4, 256, 256],
     input_shape=[None, 1],
     train=train, # train for one step
     predict=predict # make a prediction
)
```

Similary we can specify data loder like this in the same model script (`model.py`):
```python
def get_loader(traindir):
    train_dataset = datasets.ImageFolder(
        traindir,
        transforms.Compose([
            transforms.RandomResizedCrop(224),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            normalize,
        ]))
    return train_dataset

api.register(
     for='ilastik',
     type='dataloader',
     get_loader=get_loader
)
```

Importantly, the model script will allow everything provided from `pytorch` naturally, but introducing an extra YAML layer will increase the maintenance efforts on the core library unnecessary, since every loss type, optimizer etc. will be required to be wrapped as YAML keys.

**Comment by constantinpape** [comment]
> I think the model script path should be constrained to relative path only to simplify the implementation and there is no obvious benefit of allowing placing the model script elsewhere. For version control/ security purposes, we would like the script to stay with the configuration file.

I am not sure we can get away without allowing for links here. This depends on how we actually store the configuration files for entries of the model zoo:
1. Store only the configuration file in our repo. In this case, we need to allow for links in the model definition script.
2. Store link to a github repo that must contain the configuration file in root. Then we don't need to allow for links, but we don't have the config under version control ourself.
(And there might be more options to explore here).

> I think we should make it self-contained and be able to import script from the subfolders of the same github repo (relative to the root folder of the configuration file). This allows easily zip the model folder and distribute as standalone model package.

Agree, that makes sense.

> Since we are going to have the model definition script in python, and allowing import network definition from other code in github repo. I think we should consider allowing implementing the training part and data loading in the same model script.
> 
> As one can imagine that describing training and data loading in YAML can hardly scale to future cases (e.g. different preprocessing for multiple inputs channels, auxiliary loss, discriminators etc., imagine a multi-tasking network doing both classification and segmentation). On the other hand, all these can be easily solved by describing the training functions and data loaders in a script rather than YAML.

Here, I see the problem that this is linking model definition with training procedure, which are two independent things. Someone might take a model and train it on different data and with a different logic then originally done.

We could still allow to provide a default training function in the script, but that should be kept optional.

**Comment by oeway** [comment]
> I am not sure we can get away without allowing for links here. This depends on how we actually store the configuration files for entries of the model zoo:
1. Store only the configuration file in our repo. In this case, we need to allow for links in the model definition script.

It would be important to make it decentralised, meaning any github repo can host model configurations files. 

> 2. Store link to a github repo that must contain the configuration file in root. Then we don't need to allow for links, but we don't have the config under version control ourself.

If we assume all the model should be contained within a folder and the config should be placed in the root of that folder. Then a github repo can contain many model subfolders. The relative folder can always work.

```
- Github repo for models
├──  other files
├── model A
|   ├── model.config.yaml
|   └── model.py
├── model B
|   ├── model.config.yaml
|   └── model.py

```
The nice thing is that each model folder can be distributed as a standalone zip file.

How about that?

> Here, I see the problem that this is linking model definition with training procedure, which are two independent things. 

Well, I think we cannot see the model definition and training procedure as independent thing, they are tightly coupled in many case. For example, a classifier, if the last layer has `softmax` or `sigmoid` activation, you need to use the corresponding loss type. Similarly the data loader also constrained by the training procedure and the model definition. Also for models with adversarial loss or perceptual loss, the model definition are tightly coupled with training.

> Someone might take a model and train it on different data and with a different logic then originally done.

If we are targeting the end user, we don't need to consider training a model differently from what its originally way. Meanwhile, If a developer can always rewrite/modify the model script to provide a different training function.

**Comment by FynnBe** [comment]
> Well, I think we cannot see the model definition and training procedure as independent thing, they are tightly coupled in many case. For example, a classifier, if the last layer has softmax or sigmoid activation, you need to use the corresponding loss type. Similarly the data loader also constrained by the training procedure and the model definition. Also for models with adversarial loss or perceptual loss, the model definition are tightly coupled with training.

Model and training procedure are often intertwined, however there are substantially fewer ways of training models than there are models. Separating them on an abstract level brings stability and more powerful backends, allowing for hyperparameter adjustments on the fly, etc.. We should aim higher than simple 'black box' training. If training procedures are custom, simply switching the training data becomes a non-trivial development effort. There needs to be a clear API---a standard training way. 
softmax vs sigmoid etc can easily be accounted for. The config contains a valid loss anyway. Loss Criteria can be divided into groups, thus we know what kind of loss group can be applied to a given model.
Of course we will be limited in the variety of models we can train, but the core library can grow and support more and more types of models, while supporting arbitrary numbers of models that are compatible with existing training procedures without any additional development work, once the model has entered the zoo.

**Comment by constantinpape** [comment]
@FynnBe

Re Callbacks: I would place this post MVP.

Re Entry Points: Sounds like all this would work. I don't have strong feelings about this in general, but I think we should be compatible with the hubs (for torch.hub this means we would need to support a function with custom name.)

@oeway 

> ```
> - Github repo for models
> ├──  other files
> ├── model A
> |   ├── model.config.yaml
> |   └── model.py
> ├── model B
> |   ├── model.config.yaml
> |   └── model.py
> ```
> 
> 
> The nice thing is that each model folder can be distributed as a standalone zip file.
> 
> How about that?

Yes, I think that would work.


> Well, I think we cannot see the model definition and training procedure as independent thing, they are tightly coupled in many case.

Sure, the model constrains the training procedures that make sense, but there are still a lot of options.
More importantly, the model can be trained on different data, that needs a completely different data loader
(the output format of the loader needs to be the same, but data can be stored in a completely different way.)

> 
> > Someone might take a model and train it on different data and with a different logic then originally done.
> 
> If we are targeting the end user, we don't need to consider training a model differently from what its originally way. Meanwhile, a developer can always rewrite/modify the model script to provide a different training function.

Training on different data, and potentially with a different training logic, is exactly the ilastik use case, so we need to support this.
For our use-case having a training function defined in the model script will not work, because we need more control for interactive training.

I see your point though, that defining more complicated training procedures, e.g. for a GAN, in the config will be very tedious. So if we want to support more complex training procedures, there should be an option to specify a training function in the script.

**Comment by oeway** [comment]
> > We could still allow to provide a default training function in the script, but that should be kept optional.
> 
> I would go even one step further. We should rather allow for adding callbacks, so that we do not loose logging, checkpointing, etc. that a given backend may rely on (display logging, restoring checkpoints, etc. )

Good idea, since the default training function is `train for one step`, the logging can be handled by the software itself right? 

Alternatively we can also provide a set of logging api function to allow the model developer to decide when to log and make checkpoint. Something like this:
```
def train(images, target):
    ...
    api.log('training for one step %s', loss.cpu().numpy())
    api.progress(percentage)
    ...
```
> 
> Coming back to the question of an entry point.
> I do not see a need for additional logic in a `get_model` function as we want to handle weights in the backend. Because of this I am in favor of a model class.
Interestingly, I actually think the weights should also be handled by the model script. As you will see, for network with several subnetwork(e.g. a GAN), it hard to handle the weights from the backend, we would rather provide a few download/upload api to the model script so it can initialize the network and load the weight itself. In fact, not only limited to weights, the model script can also load a config file to restore the optimizer status.

A step further, since we don't know how to exactly handle the weights/config, we may also expose api to the model script to facilitate the distribution of user trained models to Zenodo. Say, the model script can register a `uploadModel` function, and the software can link to a button to allow the end user to upload and publish the trained model to Zenodo. And the model script can decide how many weights files to upload and what's their naming convention, the actual upload process is handled by the api function we provide.

> `class Model` or more realistically ```python
> class SuperNewNet:
> ....
> 
> Model = SuperNewNet
> 
> ```
> should probably be avoided.
> Specifying  a `class_name` in the config would have the benefit of being able to keep several model variations in the same file. (Something equivalent might also be achieved with specific kwargs for `get_model`, but then there would potentially be two sets of key word arguments, which might be confusing.)
> ```
I can see the advantage of using class here. However, I think the script should be self-contained, not interlinked with the yaml file. To achieve the same, I think you can add a new api function say `api.registerModelClassName()`.

**Comment by oeway** [comment]
@constantinpape 
> Training on different data, and potentially with a different training logic, is exactly the ilastik use case, so we need to support this.
For our use-case having a training function defined in the model script will not work, because we need more control for interactive training.

I see, could you elaborate on what kind of `low-level` control you would like to have to support interactive training?

Ideally, would be great if you can define these as interface, so we can support that in the model script itself. You know I would be also interested in supporting that in the `IlastikJoy` project we discussed before.

Considering the model reproducibility, one model file should ideally have exactly the same behavior across different software. Making the model file self-contained would make the model less depedent on the software or version of software, it will greatly improve the flexibility.

Otherwise, I think we an simply expose the `raw` model access to Ilastik and keep the training function for other software such as ImJoy and Fiji.

**Comment by FynnBe** [comment]
> Re Callbacks: I would place this post MVP.

yes, definitely

> Re Entry Points: Sounds like all this would work. I don't have strong feelings about this in general, but I think we should be compatible with the hubs (for torch.hub this means we would need to support a function with custom name.)

I've again looked at some examples, and I think we should not rely on hubconf.py. Model kwargs are set in the get functions and model weights loaded. Both of these we want to achieve through the config.yaml. We should be compatible with hubconf.py in the sense of not being in the way, and our model.py and hubconf.py could share code, but they---as planned atm---will not map 1 to 1.
https://github.com/NVIDIA/DeepLearningExamples/blob/torchhub/hubconf.py
https://github.com/pytorch/fairseq/blob/master/hubconf.py

**Comment by oeway** [comment]
@FynnBe 
> Model and training procedure are often intertwined, however there are substantially fewer ways of training models than there are models. Separating them on an abstract level brings stability and more powerful backends, allowing for hyperparameter adjustments on the fly, etc.. We should aim higher than simple 'black box' training. If training procedures are custom, simply switching the training data becomes a non-trivial development effort. There needs to be a clear API---a standard training way.
> softmax vs sigmoid etc can easily be accounted for. The config contains a valid loss anyway. Loss Criteria can be divided into groups, thus we know what kind of loss group can be applied to a given model.
> Of course we will be limited in the variety of models we can train, but the core library can grow and support more and more types of models, while supporting arbitrary numbers of models that are compatible with existing training procedures without any additional development work, once the model has entered the zoo.

I understand, but this will require too much maintenance effort, and the design is not future proof. Say, a new loss added to Pytorch will always require us to manually added to the core library. In terms of reproducibility, since the training are totally handled by Ilastik, the results may only be reproduced with a certain version of Ilastik at some point. 

If possibile, I think it will be much more maintainable and reproducible if we can define an interface for interactive training, and allow the model script itself to handle the interactive training.

**Comment by FynnBe** [comment]
ok, so specifying the training STEP function might be fine, the training loop, however needs to be controlled by the backend.
Then we need to specify what the step function needs to return (loss, raw output?) to be able to log these.
For interactive training, we control of the training and validation loops and the ability to adjust any hyperparameter on the fly (batch size, learning rate, etc.. ). 
the training step would need to take model and optimizer as arguments, as well as the current batch coming from the backend's dataloader. The provided training step function would need to be compatible with these inputs. If we split whatever one wants to do in this custom training step function into two or more callbacks (before prediction, after prediction/before loss, ...) it might be easier to keep stable and contain more reusable callbacks (that might be(come) part of the core library).

**Comment by FynnBe** [comment]
> Say, a new loss added to Pytorch will always require us to manually added to the core library.

All pytorch losses can easily be part of the core library as default

**Comment by FynnBe** [comment]
> In terms of reproducibility, since the training are totally handled by Ilastik, the results may only be reproduced with a certain version of Ilastik at some point.

For exact reproducibility yes. This would be the same for any training procedure specified together with the model. The version of any software used should be specified.

**Comment by FynnBe** [comment]
> If possibile, I think it will be much more maintainable and reproducible if we can define an interface for interactive training, and allow the model script itself to handle the interactive training.

the big downside to this is that every model will behave differently or the API is extensive and implementing the logic for a new model will be complex. 
If we maintain a few methods of training that models are inherently compatible with we will not loose unmaintained models over time and can provide a consistent user experience.

**Comment by oeway** [comment]
> ok, so specifying the training STEP function might be fine, the training loop, however needs to be controlled by the backend.
> Then we need to specify what the step function needs to return (loss, raw output?) to be able to log these.
> For interactive training, we control of the training and validation loops and the ability to adjust any hyperparameter on the fly (batch size, learning rate, etc.. ).
> the training step would need to take model and optimizer as arguments, as well as the current batch coming from the backend's dataloader. The provided training step function would need to be compatible with these inputs. If we split whatever one wants to do in this custom training step function into two or more callbacks (before prediction, after prediction/before loss, ...) it might be easier to keep stable and contain more reusable callbacks (that might be(come) part of the core library).

Good!
As you proposed previously, I think it's a good idea to define a base interface class for interactive training (say `api.InteractiveTraining`), and the model script can then inherit it and define the behavior.

Then the model script can be something like this:
```python
class SuperNewNet(api.InteractiveTraining):
    def __init__(self, model):
        self.model = model
        self.optimizer = ...
    def on_epoch_end(self, epoch):
        ...
    def train_step(self, batch):
         
    ...

snn = SuperNewNet()
api.register(type='model', model=snn)
```

> the big downside to this is that every model will behave differently or the API is extensive and implementing the logic for a new model will be complex.
If we maintain a few methods of training that models are inherently compatible with we will not loose unmaintained models over time and can provide a consistent user experience.

You can think of doing this is just to allow the model script to override the default training behavior. It shouldn't be too different than you are doing right now. Say you have already a class named `InteractiveTraining` inside Ilastik with all the default training functions. Now what you need to do is to expose that class to allow the model script override the training functions.

For those standard models, we can still use the default training functions:
```
snn = api.InteractiveTraining(model=..)
api.register(type='model', model=snn)
```

**Comment by oeway** [comment]
> > Say, a new loss added to Pytorch will always require us to manually added to the core library.
> 
> All pytorch losses can easily be part of the core library as default

Sure, it will be naturally to support in the model script, but if we rely on the YAML config, it will be difficult to expose all future loss types as YAML keys automatically, and you also mentioned that we can define rules to group the loss functions, that's also hard without manually adding them.

**Comment by constantinpape** [comment]
@oeway 
Let's back up from the detailed discussion a bit. We are discussing two fairly different design patterns here.
What the ilastik group has initially envisioned is to have a declarative (yaml) config, that only allows to define the model in code (because a framework independent model definition is too tedious).

You are suggesting to define API's for different functionalities, like `InteractiveTraining` etc.
There's a lot of pros and cons to this design choice and I don't have a complete overview of this.

Some of my key considerations:
Advantages of the declarative config over the API design:
1.  Having the declarative config is more stable and easier to automatically validate (there's less custom code involved, so also less things that need to be tested for every model).
2. The declarative config can be fairly minimal in the beginning and then be expanded in the future (e.g. by allowing for a new key that specifies `Callbacks`). 
3. If we have a central config, we don't need to implement APIs for different softwares that can work with the model zoo. There's one config that holds the information + model definition, there's some convenience functions in the core library to load it, that's it.

Advantages of API over (only) config:
1. Adding the API makes everything more permissive and allows to express more 'custom' use-cases, e.g. GANs, multiple losses etc. and generally makes interaction with custom code easier.
2. It allows different sofwares to express functionality in a similar way, having more reproducibility between them.
3. It allows parts of the definitions / config in code, which can be easier to generate (but can also be a disadvantage, because it makes configs harder to validate).

I think that from the ilastik side, we really want to have stable and easy to maintain model definitions that can be shipped to users who don't have any deep learning experience, which is why we favor the declarative config. Also, in the beginning we will only support segmentation tasks.
I can see that not being able to express more custom use cases might be a big issue in general.

@FynnBe and I, think that it's not a good time to make this design decision already, because we would like to have something working first to and be more informed then.
Would you be ok with sticking with only the config for now (which means only supporting simple use cases like classification and segmentation in the MVP). We can then discuss this more at the hackathon and see what we will need post MVP.

**Comment by oeway** [comment]
@constantinpape 

Thanks for the nice summary!
Yes, we need to make the decision on the design pattern before going into details.

I would like to add also for the API pattern, the model script can define test functions to allow validate the models( Kipoi also support test apis). Another advantage of doing it in API over config is that you can use your code editor to do autocompletion during development.

I can completely understand Ilastik prefer declarative approach since you have a well defined scope on the model types. And as you see that the config approach may not fit well for Fiji and ImJoy.

Meanwhile I think we can figure out a way to allow the two patterns co-exist. If we provide a set of predefined model scripts in the core library, then we can use declarative config file and used with a default model script for Ilastik. 

Coming back to the discussion about the link to the model script before, if we allow http link to model script, then default Ilastik specific model scripts can be hosted from the Ilastik project repo, and you can manage the model script, all the models configurations hosted elsewhere can just refer to that link, and declear all the training/data options in YAML only. It also allow you to upgrade easily, say, to avoid breaking existing model config files, you can add new version of model scripts, and new model config files can refer to the new ones.

How about that?

**Comment by constantinpape** [comment]
> Thanks for the nice summary!
> Yes, we need to make the decision on the design pattern before going into details.

Sorry, I should have probably put the last paragraph in the beginning, but I would argue not to make this decision right now. My logic is the following: we will need some basic yaml config in any case and we can just start from that using it as our declarative config.

Once we have a few initial models (segmentation and classification) that works with this, we have a better basis for discussion already and can see how to build on this.

**Comment by oeway** [comment]
@constantinpape @FynnBe Thanks for the demo you have made in the current repo.

Based on the use case you made in this repo, me and @MartinHjelmare will try to work on a prototype model engine which works for both the API pattern and the declarative style.

For a better discussion basis, we will try to explore:
1. making use of the Jupyter project in order to benefit from existing infrastructure (Binder/Google Colab etc.)
2. potentially support Java/Fiji and R or other languages through Jupyter
3. support ImJoy, potentially drop our [plugin engine](https://github.com/oeway/ImJoy-Engine) and use only the generalized model engine
4. optionally, solve pip/conda dependencies and support virtual environments

The model engine will be run either with the same python runtime as the software (e.g. for Ilastik), or a standalone python runtime (for ImJoy and Fiji).

To support declarative style, you just need to provide a model script which parses the options in yaml.

**Comment by constantinpape** [comment]
This discussion got super-seeded by the discussions at the hackathon, closing it for now.
